global using Autogenerated;
global using OpenTK.Graphics.OpenGL;
using CommandLine;
using GPUAcceleratedNormalGenerator.Shaders;
using SharpShaders;
using SharpShaders.Textures;
using System.Diagnostics;
using System.Reflection.Metadata.Ecma335;

namespace GPUAcceleratedNormalGenerator
{
    internal class Program
    {
        // Public static access for your OpenTK rendering/compute engine
        public static Options Options { get; private set; } = new Options();

        public static int Main(string[] args)
        {
            var result = Parser.Default.ParseArguments<Options>(args)
                .WithParsed(Run)
                .WithNotParsed(errors => Environment.ExitCode = 1);

            return Environment.ExitCode;
        }

        private static void Run(Options parsedOptions)
        {
            Options = parsedOptions;

            // Print the arguments
            Console.WriteLine($"[Config] InputPath: '{Options.InputPath}'");
            Console.WriteLine($"[Config] OutputPath: '{Options.OutputPath}'");
            Console.WriteLine($"[Config] HeightmapOutputPath: '{Options.HeightmapOutputPath}'");
            Console.WriteLine($"[Config] Strength: {Options.Strength}");
            Console.WriteLine($"[Config] BatchFilePath: '{Options.BatchFilePath}'");
            Console.WriteLine($"[Config] MaxBatchSize: {Options.MaxBatchSize}");
            Console.WriteLine($"[Config] SaveHeightMapsForBatch: {Options.SaveHeightMapsForBatch}");
            Console.WriteLine($"[Config] SaveBlursForBatch: {Options.SaveBlursForBatch}");

            bool hasSingleInput = !string.IsNullOrEmpty(Options.InputPath);
            bool hasBatchFile = !string.IsNullOrEmpty(Options.BatchFilePath);

            // Handle invalid combinations: both specified or neither specified
            if (hasSingleInput && hasBatchFile)
            {
                Console.WriteLine("[Error] Cannot specify both single input (-i) and batch file (-f) simultaneously.");
                Environment.ExitCode = 1;
                return;
            }

            if (!hasSingleInput && !hasBatchFile)
            {
                Console.WriteLine("[Error] Missing required input. Specify either a single input (-i) or a batch file (-f).");
                Environment.ExitCode = 1;
                return;
            }

            if (hasSingleInput && string.IsNullOrEmpty(Options.OutputPath))
            {
                Console.WriteLine("[Error] Output path (-o) is required when using single-input mode.");
                Environment.ExitCode = 1;
                return;
            }

            try
            {
                SharpS.LibLogWriter = Console.Out;
                SharpS.OpenOGL();

                if (hasBatchFile)
                {
                    BatchProcessing();
                }
                else
                {
                    SingleProcessing();
                }
                Console.WriteLine("[Success] Normal map generated successfully.");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"[Error] Processing failed: {ex.Message}");
                Environment.ExitCode = 1;
            }
        }

        private static void SingleProcessing()
        {
            // since these methods use texture arrays, wwe pack it in an array
            Texture src = Texture.LoadTextureArray([Options.InputPath]);

            Texture hmap = HeightMap.Convert(src, 1);
            Options.HeightmapOutputPath.ExecuteIfNotNull(hmap.SaveToFile);
            Texture normal = NormalMap.Convert(hmap, 1, Options.Strength);
            normal.SaveToFile(Options.OutputPath);
        }

        private static void BatchProcessing()
        {
            Stopwatch stopwatch = Stopwatch.StartNew();

            List<BatchTask> tasks = PSVParser.LoadAndValidateBatchFile(Options.BatchFilePath);

            List<IEnumerable<BatchTask>> groupedTasks = tasks.Select((t, i) => new { val = t, index = i })
                .GroupBy(s => s.index / Options.MaxBatchSize)
                .Select(s => s.Select(z => z.val))
                .ToList();

            foreach (IEnumerable<BatchTask> taskBatch in groupedTasks)
            {
                string[] sources = taskBatch.Select(s => s.SourcePath).ToArray();
                string[] heightmapPaths = taskBatch.Select(s => s.HeightmapPath ?? string.Empty).ToArray();
                string[] blurPaths = taskBatch.Select(s => s.BlurPath ?? string.Empty).ToArray();
                string[] normalPaths = taskBatch.Select(s => s.NormalPath).ToArray();


                int layerCount = sources.Length;
                const bool parallel = true;


                using Texture batchImage = Texture.LoadTextureArray(sources, expandToFit: true, parallel: parallel);

                using Texture hmap = HeightMap.Convert(batchImage, layerCount);
                Options.SaveHeightMapsForBatch.ExecuteIf(() => hmap.SaveLayersToFiles(heightmapPaths, parallel: parallel));
                batchImage.Dispose(); // best to dispose already used things to not waste vram intermediately

                using Texture blurs = Blur.Convert(hmap, layerCount);
                Options.SaveBlursForBatch.ExecuteIf(() => blurs.SaveLayersToFiles(blurPaths));
                hmap.Dispose();

                using Texture normals = NormalMap.Convert(blurs, layerCount);
                normals.SaveLayersToFiles(normalPaths);
            }

            TimeSpan ts = stopwatch.Elapsed;
            string elapsed = $"{ts.Hours:D2}h {ts.Minutes:D2}m {ts.Seconds:D2}s {ts.Milliseconds}ms";

            Console.WriteLine(elapsed);
        }
    }
}
