#version 430 core

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(binding = 0) uniform sampler2DArray u_InputTexture;

layout(r32f, binding = 0) writeonly uniform image2DArray u_OutputImage;

uniform float u_BlurRadius;

void main()
{
    // TODO: improve blur logic
    ivec3 coords = ivec3(gl_GlobalInvocationID.xyz);
    ivec3 size = imageSize(u_OutputImage);

    if (coords.x >= size.x || coords.y >= size.y || coords.z >= size.z)
        return;

    vec2 texSize = vec2(size.xy);
    vec2 uv = (vec2(coords.xy) + 0.5f) / texSize;
    int layer = coords.z;

    float sum = 0.0f;
    float weightSum = 0.0f;
    
    int range = 2;
    for (int x = -range; x <= range; x++)
    {
        for (int y = -range; y <= range; y++)
        {
            vec2 offset = vec2(float(x), float(y)) * u_BlurRadius / texSize;
            float sampleVal = texture(u_InputTexture, vec3(uv + offset, float(layer))).r;
            
            float weight = exp(-(x * x + y * y) / (2.0f * range * range));
            
            sum += sampleVal * weight;
            weightSum += weight;
        }
    }

    float blurredValue = sum / weightSum;

    imageStore(u_OutputImage, coords, vec4(blurredValue, 0.0, 0.0, 0.0));
}